name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: beer pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_VERSION: 16.13.0
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Run tests and package the application
        run: |
          chmod +x mvnw
          ./mvnw clean verify -Pprod
